# Generated by Django 5.2.6 on 2025-09-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("author", "0003_alter_author_nationality"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(max_length=20, verbose_name="ISBN")),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                ("publish_date", models.DateField(verbose_name="Publish Date")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Fiction", "FICTION"),
                            ("Fantasy", "FANTASY"),
                            ("Mystery", "MYSTERY"),
                            ("Romance", "ROMANCE"),
                            ("Biography", "BIOGRAPHY"),
                            ("Science", "SCIENCE"),
                        ],
                        verbose_name="Gender",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Price"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="author.author",
                        verbose_name="Author",
                    ),
                ),
            ],
        ),
    ]
