# Generated by Django 5.2.6 on 2025-09-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=20, unique=True, verbose_name="ISBN"),
        ),
    ]
