# Generated by Django 5.2.6 on 2025-09-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_book_isbn"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
    ]
