# Generated by Django 5.2.6 on 2025-09-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("date_of_birth", models.DateField(verbose_name="Date of birth")),
                (
                    "nationality",
                    models.CharField(
                        choices=[
                            ("Fiction", "FICTION"),
                            ("Fantasy", "FANTASY"),
                            ("Mystery", "MYSTERY"),
                            ("Romance", "ROMANCE"),
                            ("Biography", "BIOGRAPHY"),
                            ("Science", "SCIENCE"),
                        ],
                        max_length=20,
                        verbose_name="Nationality",
                    ),
                ),
            ],
        ),
    ]
