# Generated by Django 5.2.6 on 2025-09-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0002_author_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="nationality",
            field=models.CharField(
                choices=[
                    ("American", "American"),
                    ("British", "British"),
                    ("Canadian", "Canadian"),
                    ("French", "French"),
                    ("German", "German"),
                    ("Indian", "Indian"),
                    ("Japanese", "Japanese"),
                    ("Russian", "Russian"),
                    ("Spanish", "Spanish"),
                    ("Other", "Other"),
                ],
                max_length=20,
                verbose_name="Nationality",
            ),
        ),
    ]
